---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/demaconsulting/NuGetCacheTool
    about: Read the documentation for NuGetCacheTool
  - name: 💬 Discussions
    url: https://github.com/demaconsulting/NuGetCacheTool/discussions
    about: Ask questions and discuss with the community
