package NuGetCacheTool {
    part def Program {
        doc /* Entry point and application orchestrator. */

        comment sourceRef /* Source: src/DemaConsulting.NuGet.CacheTool/Program.cs */
        comment testRef /* Test: test/DemaConsulting.NuGet.CacheTool.Tests/ProgramTests.cs */
        comment designRef /* Design: docs/design/nuget-cache-tool/program.md */
        comment verificationRef /* Verification: docs/verification/nuget-cache-tool/program.md */
        comment reqRef /* Requirements: docs/reqstream/nuget-cache-tool/program.yaml */
    }
}
